# ---- user's settings -------------------------------------------------------

TARGET      = helloworld.dll
FAR_EXPORTS = OPENPLUGINW
PATH_LUAFAR = ..\..

# ---- end of user's settings ------------------------------------------------

include $(PATH_LUAFAR)/src/luaplug.mak

# (end of Makefile)
